### ISSUE TITLE
No lxml

### ISSUE THREAD

**Issue by timClicks** [elishowk/cablegate_semnet#7]
Strongly recommend using [lxml.html](http://codespeak.net/lxml/lxmlhtml.html) over BeautifulSoup. It's written in C, and is a _much_ faster parser.

**Comment by elishowk** [comment]
May be for the next version, thanks.
Have to finish a first version for a presentation at the FOSDEM this saturday.
I keep it in mind.

**Comment by timClicks** [comment]
ha, of course! have a great weekend

**Comment by heuer** [comment]
I used lxml in an early version of https://github.com/heuer/cablemap and switched to regular expressions which are faster than BeatifulSoup and lxml.html. 
You cannot extract much information from the HTML page (originator, creation date, release date, classification) and this can be done with regexes much better without external dependencies.

**Comment by elishowk** [comment]
done for while
